---
title: "Proyecto Experimentos"
output: html_document
date: "2025-06-21"
---

```{r}
library(readxl)
base_aguacates <- read_excel("C:/Users/XPC/Downloads/base.aguacates.xlsx")
```


```{r}
base_aguacates$temp=as.factor(base_aguacates$temp)
levels(base_aguacates$temp)=c("ambiente","refrigeradora","congelador") 
base_aguacates$semilla=factor(base_aguacates$semilla) 
levels(base_aguacates$semilla)=c("con semilla","sin semilla")
base_aguacates$bloque = as.factor(base_aguacates$bloque)
attach(base_aguacates)
```


número de repeticiones por tratamiento.
```{r}
table(base_aguacates$temp,base_aguacates$semilla)
```


ggplot de interacción
```{r}
library(ggplot2)
ggplot(base_aguacates,aes(x=semilla,y=oxidación, group= temp))+
  stat_summary(fun.y = "mean",geom="line", aes(linetype = temp))
```


paso a suma nula y modelo
```{r}
options(contrasts = c("contr.sum","contr.poly"))
mod= lm(oxidación~temp*semilla+bloque, data=base_aguacates)
```


```{r}
anova(mod)
```


```{r}
boxplot(oxidación~temp+semilla, ylab = "Nivel de Oxidación", xlab = "Temperatura : Semilla", data = base_aguacates)
```


$$
\mu_{ijk} = \mu + \alpha_i+\beta_j+(\alpha\beta)_{ij}+\delta_k\\
$$
$$
\mu_{ijk} = \mu + \alpha_1 T_1 + \alpha_2 T_2 + \beta_1 C_1 + (\alpha\beta)_{11} T_1 C_1 + (\alpha\beta)_{21} T_2 C_1 + \delta_k
$$
#prueba
```{r}
modprueba=lm(oxidación~bloque,data=base_aguacates) #fijo respuesta y bloque
pre=predict(modprueba)  #me da la media de cada bloque
t1=base_aguacates$oxidación-pre+mean(base_aguacates$oxidación)
```

```{r}
par(mfrow=c(1,2))
boxplot(oxidación~temp,ylim=c(0,6),xlab="temp",ylab="oxidación",data=base_aguacates)
boxplot(t1~temp,ylim=c(0,6),xlab="temp",
ylab="oxidacion centrada",data=base_aguacates)
```

